name: SteamDealBot

# Run the bot every 6 hours
on:
  schedule:
    # Cron format: minute hour day month day-of-week
    # This runs at 00:00, 06:00, 12:00, and 18:00 UTC every day
    - cron: '0 */6 * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run SteamDealBot
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      run: |
        python bot.py
        
    - name: Bot execution summary
      if: always()
      run: |
        echo "🤖 SteamDealBot execution completed!"
        echo "📅 Timestamp: $(date)"
        echo "🔄 Next run scheduled for 6 hours from now"

